apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insurance-ai-production

resources:
- ../../base

patchesStrategicMerge:
- production-config.yaml
- production-secrets.yaml

replicas:
- name: backend-deployment
  count: 3
- name: frontend-deployment
  count: 2
- name: nginx-deployment
  count: 2

images:
- name: insurance-ai-backend
  newTag: production-latest
- name: insurance-ai-frontend
  newTag: production-latest

configMapGenerator:
- name: production-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO
  - DEBUG=false
  - DATABASE_POOL_SIZE=20
  - REDIS_POOL_SIZE=10
  - MAX_WORKERS=4
  - RATE_LIMIT_REQUESTS=1000
  - RATE_LIMIT_WINDOW=3600

secretGenerator:
- name: production-secrets
  literals:
  - DATABASE_PASSWORD=CHANGE_ME_IN_PRODUCTION
  - REDIS_PASSWORD=CHANGE_ME_IN_PRODUCTION
  - JWT_SECRET_KEY=CHANGE_ME_IN_PRODUCTION
  - ENCRYPTION_KEY=CHANGE_ME_IN_PRODUCTION

