# Alerting provisioning
apiVersion: 1

# Contact points
contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: default-email-receiver
        type: email
        settings:
          addresses: admin@example.com
        disableResolveMessage: false

# Notification policies
policies:
  - orgId: 1
    receiver: default-email
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h

# Alert rules (optional - you can add specific rules here)
groups:
  - orgId: 1
    name: "Insurance System Alerts"
    folder: "alerts"
    interval: 1m
    rules:
      - uid: high-error-rate
        title: "High Error Rate"
        condition: A
        data:
          - refId: A
            queryType: prometheus
            relativeTimeRange:
              from: 300
              to: 0
            model:
              expr: 'rate(api_requests_total{status=~"5.."}[5m]) > 0.1'
              interval: ""
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Error rate is above 10% for the last 5 minutes"
          summary: "High error rate detected"
        labels:
          severity: warning
