apiVersion: v1
kind: Secret
metadata:
  name: insurance-ai-secrets
  namespace: insurance-ai
  labels:
    app.kubernetes.io/name: insurance-ai-system
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database Credentials
  DATABASE_USERNAME: "insurance_user"
  DATABASE_PASSWORD: "secure_db_password_change_in_production"
  DATABASE_URL: "postgresql://insurance_user:secure_db_password_change_in_production@postgres-service:5432/insurance_ai_system"
  
  # Redis Password
  REDIS_PASSWORD: "secure_redis_password_change_in_production"
  REDIS_URL: "redis://:secure_redis_password_change_in_production@redis-service:6379/0"
  
  # JWT Secrets
  JWT_SECRET_KEY: "your-super-secret-jwt-key-change-in-production-min-32-chars"
  JWT_REFRESH_SECRET_KEY: "your-super-secret-refresh-key-change-in-production-min-32-chars"
  
  # Encryption Keys
  ENCRYPTION_KEY: "your-32-character-encryption-key-change-in-production"
  PASSWORD_SALT: "your-password-salt-change-in-production"
  
  # External Service API Keys
  OPENAI_API_KEY: "your-openai-api-key-here"
  AZURE_COGNITIVE_SERVICES_KEY: "your-azure-cognitive-services-key"
  AZURE_COGNITIVE_SERVICES_ENDPOINT: "https://your-region.api.cognitive.microsoft.com/"
  
  # Email Configuration
  SMTP_USERNAME: "your-smtp-username"
  SMTP_PASSWORD: "your-smtp-password"
  EMAIL_FROM: "noreply@zurich.com"
  
  # SMS Configuration
  SMS_API_KEY: "your-sms-api-key"
  SMS_API_SECRET: "your-sms-api-secret"
  SMS_FROM_NUMBER: "+1234567890"
  
  # OAuth Configuration
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  MICROSOFT_CLIENT_ID: "your-microsoft-client-id"
  MICROSOFT_CLIENT_SECRET: "your-microsoft-client-secret"
  
  # Monitoring and Logging
  PROMETHEUS_PASSWORD: "secure_prometheus_password"
  GRAFANA_ADMIN_PASSWORD: "secure_grafana_password"
  
  # File Storage
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  AWS_S3_BUCKET: "insurance-ai-documents"
  AWS_REGION: "us-east-1"
  
  # Backup Configuration
  BACKUP_ENCRYPTION_KEY: "your-backup-encryption-key-32-chars"
  BACKUP_S3_BUCKET: "insurance-ai-backups"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: insurance-ai
  labels:
    app.kubernetes.io/name: insurance-ai-system
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: "insurance_ai_system"
  POSTGRES_USER: "insurance_user"
  POSTGRES_PASSWORD: "secure_db_password_change_in_production"
  POSTGRES_INITDB_ARGS: "--auth-host=md5"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: insurance-ai
  labels:
    app.kubernetes.io/name: insurance-ai-system
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  REDIS_PASSWORD: "secure_redis_password_change_in_production"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: insurance-ai
  labels:
    app.kubernetes.io/name: insurance-ai-system
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Replace with actual certificate data in production
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...

